local _local_1_ = require("neovim.colorutils")
local blend_hex = _local_1_["blend-hex"]
if vim.g.colors_name then
  vim.cmd.hi("clear")
else
end
vim.g["colors_name"] = "neovim"
vim.o["termguicolors"] = true
local base00 = "#07080d"
local base06 = "#ffffff"
local base09 = "#fce094"
local neovim = (((vim.o.background == "dark") and {base00 = base00, base01 = blend_hex(base00, base06, 0.085), base02 = blend_hex(base00, base06, 0.18), base03 = blend_hex(base00, base06, 0.3), base04 = blend_hex(base00, base06, 0.82), base05 = blend_hex(base00, base06, 0.95), base06 = base06, base07 = "#8cf8f7", base08 = "#ffc0b9", base09 = base09, base10 = "#ffcaea", base11 = "#a6dbff", base12 = "#9b9ea4", base13 = "#b3f6c0", base14 = "#ffdb6e", base15 = "#82cfff", blend = "#131313", none = "NONE"}) or {base00 = base06, base01 = blend_hex(base00, base06, 0.95), base02 = blend_hex(base00, base06, 0.82), base03 = base00, base04 = "#37474F", base05 = "#90A4AE", base06 = "#525252", base07 = "#08bdba", base08 = "#ff7eb6", base09 = "#ee5396", base10 = "#FF6F00", base11 = "#0f62fe", base12 = "#673AB7", base13 = "#42be65", base14 = "#be95ff", base15 = "#FFAB91", blend = "#FAFAFA", none = "NONE"})
vim.g["terminal_color_0"] = neovim.base01
vim.g["terminal_color_1"] = neovim.base11
vim.g["terminal_color_2"] = neovim.base14
vim.g["terminal_color_3"] = neovim.base13
vim.g["terminal_color_4"] = neovim.base09
vim.g["terminal_color_5"] = neovim.base15
vim.g["terminal_color_6"] = neovim.base08
vim.g["terminal_color_7"] = neovim.base05
vim.g["terminal_color_8"] = neovim.base03
vim.g["terminal_color_9"] = neovim.base11
vim.g["terminal_color_10"] = neovim.base14
vim.g["terminal_color_11"] = neovim.base13
vim.g["terminal_color_12"] = neovim.base09
vim.g["terminal_color_13"] = neovim.base15
vim.g["terminal_color_14"] = neovim.base07
vim.g["terminal_color_15"] = neovim.base06
vim.api.nvim_set_hl(0, "ColorColumn", {fg = neovim.none, bg = neovim.base01})
vim.api.nvim_set_hl(0, "Cursor", {fg = neovim.base00, bg = neovim.base04})
vim.api.nvim_set_hl(0, "CursorLine", {fg = neovim.none, bg = neovim.base01})
vim.api.nvim_set_hl(0, "CursorColumn", {fg = neovim.none, bg = neovim.base01})
vim.api.nvim_set_hl(0, "CursorLineNr", {fg = neovim.base04, bg = neovim.none})
vim.api.nvim_set_hl(0, "QuickFixLine", {fg = neovim.none, bg = neovim.base01})
vim.api.nvim_set_hl(0, "Error", {fg = neovim.base10, bg = neovim.base01})
vim.api.nvim_set_hl(0, "LineNr", {fg = neovim.base03, bg = neovim.base00})
vim.api.nvim_set_hl(0, "NonText", {fg = neovim.base02, bg = neovim.none})
vim.api.nvim_set_hl(0, "Normal", {fg = neovim.base04, bg = neovim.base00})
vim.api.nvim_set_hl(0, "Pmenu", {fg = neovim.base04, bg = neovim.base01})
vim.api.nvim_set_hl(0, "PmenuSbar", {fg = neovim.base04, bg = neovim.base01})
vim.api.nvim_set_hl(0, "PmenuSel", {fg = neovim.base08, bg = neovim.base02})
vim.api.nvim_set_hl(0, "PmenuThumb", {fg = neovim.base08, bg = neovim.base02})
vim.api.nvim_set_hl(0, "SpecialKey", {fg = neovim.base03, bg = neovim.none})
vim.api.nvim_set_hl(0, "Visual", {fg = neovim.none, bg = neovim.base02})
vim.api.nvim_set_hl(0, "VisualNOS", {fg = neovim.none, bg = neovim.base02})
vim.api.nvim_set_hl(0, "TooLong", {fg = neovim.none, bg = neovim.base02})
vim.api.nvim_set_hl(0, "Debug", {fg = neovim.base13, bg = neovim.none})
vim.api.nvim_set_hl(0, "Macro", {fg = neovim.base07, bg = neovim.none})
vim.api.nvim_set_hl(0, "MatchParen", {fg = neovim.none, bg = neovim.base02, underline = true})
vim.api.nvim_set_hl(0, "Bold", {fg = neovim.none, bg = neovim.none, bold = true})
vim.api.nvim_set_hl(0, "Italic", {fg = neovim.none, bg = neovim.none, italic = true})
vim.api.nvim_set_hl(0, "Underlined", {fg = neovim.none, bg = neovim.none, underline = true})
vim.api.nvim_set_hl(0, "DiagnosticWarn", {fg = neovim.base14, bg = neovim.none})
vim.api.nvim_set_hl(0, "DiagnosticError", {fg = neovim.base10, bg = neovim.none})
vim.api.nvim_set_hl(0, "DiagnosticInfo", {fg = neovim.base09, bg = neovim.none})
vim.api.nvim_set_hl(0, "DiagnosticHint", {fg = neovim.base04, bg = neovim.none})
vim.api.nvim_set_hl(0, "DiagnosticUnderlineWarn", {fg = neovim.base14, bg = neovim.none, undercurl = true})
vim.api.nvim_set_hl(0, "DiagnosticUnderlineError", {fg = neovim.base10, bg = neovim.none, undercurl = true})
vim.api.nvim_set_hl(0, "DiagnosticUnderlineInfo", {fg = neovim.base04, bg = neovim.none, undercurl = true})
vim.api.nvim_set_hl(0, "DiagnosticUnderlineHint", {fg = neovim.base04, bg = neovim.none, undercurl = true})
vim.api.nvim_set_hl(0, "HealthError", {fg = neovim.base10, bg = neovim.none})
vim.api.nvim_set_hl(0, "HealthWarning", {fg = neovim.base14, bg = neovim.none})
vim.api.nvim_set_hl(0, "HealthSuccess", {fg = neovim.base13, bg = neovim.none})
vim.api.nvim_set_hl(0, "@comment", {link = "Comment"})
vim.api.nvim_set_hl(0, "@text.literal.commodity", {fg = neovim.base13, bg = neovim.none})
vim.api.nvim_set_hl(0, "@number", {fg = neovim.base09, bg = neovim.none})
vim.api.nvim_set_hl(0, "@number.date", {fg = neovim.base08, bg = neovim.none})
vim.api.nvim_set_hl(0, "@number.date.effective", {fg = neovim.base13, bg = neovim.none})
vim.api.nvim_set_hl(0, "@number.interval", {fg = neovim.base09, bg = neovim.none})
vim.api.nvim_set_hl(0, "@number.status", {fg = neovim.base12, bg = neovim.none})
vim.api.nvim_set_hl(0, "@number.quantity", {fg = neovim.base11, bg = neovim.none})
vim.api.nvim_set_hl(0, "@number.quantity.negative", {fg = neovim.base10, bg = neovim.none})
vim.api.nvim_set_hl(0, "LspCodeLens", {fg = neovim.none, bg = neovim.base03})
vim.api.nvim_set_hl(0, "LspReferenceText", {fg = neovim.none, bg = neovim.base03})
vim.api.nvim_set_hl(0, "LspReferenceread", {fg = neovim.none, bg = neovim.base03})
vim.api.nvim_set_hl(0, "LspReferenceWrite", {fg = neovim.none, bg = neovim.base03})
vim.api.nvim_set_hl(0, "LspSignatureActiveParameter", {fg = neovim.base08, bg = neovim.none})
vim.api.nvim_set_hl(0, "@lsp.type.class", {link = "Structure"})
vim.api.nvim_set_hl(0, "@lsp.type.decorator", {link = "Decorator"})
vim.api.nvim_set_hl(0, "@lsp.type.decorator.markdown", {link = "Structure"})
vim.api.nvim_set_hl(0, "@lsp.type.function", {link = "@function"})
vim.api.nvim_set_hl(0, "@lsp.type.macro", {link = "Macro"})
vim.api.nvim_set_hl(0, "@lsp.type.method", {link = "@function"})
vim.api.nvim_set_hl(0, "@lsp.type.struct", {link = "Structure"})
vim.api.nvim_set_hl(0, "@lsp.type.type", {link = "Type"})
vim.api.nvim_set_hl(0, "@lsp.type.typeParameter", {link = "Typedef"})
vim.api.nvim_set_hl(0, "@lsp.type.selfParameter", {link = "@variable.builtin"})
vim.api.nvim_set_hl(0, "@lsp.type.builtinConstant", {link = "@constant.builtin"})
vim.api.nvim_set_hl(0, "@lsp.type.magicFunction", {link = "@function.builtin"})
vim.api.nvim_set_hl(0, "@lsp.type.boolean", {link = "@boolean"})
vim.api.nvim_set_hl(0, "@lsp.type.builtinType", {link = "@type.builtin"})
vim.api.nvim_set_hl(0, "@lsp.type.comment", {link = "@comment"})
vim.api.nvim_set_hl(0, "@lsp.type.enum", {link = "@type"})
vim.api.nvim_set_hl(0, "@lsp.type.enumMember", {link = "@constant"})
vim.api.nvim_set_hl(0, "@lsp.type.escapeSequence", {link = "@string.escape"})
vim.api.nvim_set_hl(0, "@lsp.type.formatSpecifier", {link = "@punctuation.special"})
vim.api.nvim_set_hl(0, "@lsp.type.keyword", {link = "@keyword"})
vim.api.nvim_set_hl(0, "@lsp.type.namespace", {link = "@namespace"})
vim.api.nvim_set_hl(0, "@lsp.type.number", {link = "@number"})
vim.api.nvim_set_hl(0, "@lsp.type.operator", {link = "@operator"})
vim.api.nvim_set_hl(0, "@lsp.type.parameter", {link = "@parameter"})
vim.api.nvim_set_hl(0, "@lsp.type.property", {link = "@property"})
vim.api.nvim_set_hl(0, "@lsp.type.selfKeyword", {link = "@variable.builtin"})
vim.api.nvim_set_hl(0, "@lsp.type.string.rust", {link = "@string"})
vim.api.nvim_set_hl(0, "@lsp.type.typeAlias", {link = "@type.definition"})
vim.api.nvim_set_hl(0, "@lsp.type.unresolvedReference", {link = "Error"})
vim.api.nvim_set_hl(0, "@lsp.type.variable", {link = "@variable"})
vim.api.nvim_set_hl(0, "@lsp.mod.readonly", {link = "@constant"})
vim.api.nvim_set_hl(0, "@lsp.mod.typeHint", {link = "Type"})
vim.api.nvim_set_hl(0, "@lsp.mod.builtin", {link = "Special"})
vim.api.nvim_set_hl(0, "@lsp.typemod.class.defaultLibrary", {link = "@type.builtin"})
vim.api.nvim_set_hl(0, "@lsp.typemod.enum.defaultLibrary", {link = "@type.builtin"})
vim.api.nvim_set_hl(0, "@lsp.typemod.enumMember.defaultLibrary", {link = "@constant.builtin"})
vim.api.nvim_set_hl(0, "@lsp.typemod.function.defaultLibrary", {link = "@function.builtin"})
vim.api.nvim_set_hl(0, "@lsp.typemod.keyword.async", {link = "@keyword.coroutine"})
vim.api.nvim_set_hl(0, "@lsp.typemod.macro.defaultLibrary", {link = "@function.builtin"})
vim.api.nvim_set_hl(0, "@lsp.typemod.method.defaultLibrary", {link = "@function.builtin"})
vim.api.nvim_set_hl(0, "@lsp.typemod.operator.injected", {link = "@operator"})
vim.api.nvim_set_hl(0, "@lsp.typemod.string.injected", {link = "@string"})
vim.api.nvim_set_hl(0, "@lsp.typemod.operator.controlFlow", {link = "@exception"})
vim.api.nvim_set_hl(0, "@lsp.typemod.keyword.documentation", {link = "Special"})
vim.api.nvim_set_hl(0, "@lsp.typemod.variable.global", {link = "@constant"})
vim.api.nvim_set_hl(0, "@lsp.typemod.variable.static", {link = "@constant"})
vim.api.nvim_set_hl(0, "@lsp.typemod.variable.defaultLibrary", {link = "Special"})
vim.api.nvim_set_hl(0, "@lsp.typemod.function.builtin", {link = "@function.builtin"})
vim.api.nvim_set_hl(0, "@lsp.typemod.function.readonly", {link = "@method"})
vim.api.nvim_set_hl(0, "@lsp.typemod.variable.defaultLibrary", {link = "@variable.builtin"})
vim.api.nvim_set_hl(0, "@lsp.typemod.variable.injected", {link = "@variable"})
vim.api.nvim_set_hl(0, "Folded", {fg = neovim.base02, bg = neovim.base01})
vim.api.nvim_set_hl(0, "FoldColumn", {fg = neovim.base01, bg = neovim.base00})
vim.api.nvim_set_hl(0, "SignColumn", {fg = neovim.base01, bg = neovim.base00})
vim.api.nvim_set_hl(0, "Directory", {fg = neovim.base08, bg = neovim.none})
vim.api.nvim_set_hl(0, "EndOfBuffer", {fg = neovim.base01, bg = neovim.none})
vim.api.nvim_set_hl(0, "ErrorMsg", {fg = neovim.base10, bg = neovim.none})
vim.api.nvim_set_hl(0, "ModeMsg", {fg = neovim.base04, bg = neovim.none})
vim.api.nvim_set_hl(0, "MoreMsg", {fg = neovim.base08, bg = neovim.none})
vim.api.nvim_set_hl(0, "Question", {fg = neovim.base04, bg = neovim.none})
vim.api.nvim_set_hl(0, "Substitute", {fg = neovim.base01, bg = neovim.base08})
vim.api.nvim_set_hl(0, "WarningMsg", {fg = neovim.base14, bg = neovim.none})
vim.api.nvim_set_hl(0, "WildMenu", {fg = neovim.base08, bg = neovim.base01})
vim.api.nvim_set_hl(0, "helpHyperTextJump", {fg = neovim.base08, bg = neovim.none})
vim.api.nvim_set_hl(0, "helpSpecial", {fg = neovim.base09, bg = neovim.none})
vim.api.nvim_set_hl(0, "helpHeadline", {fg = neovim.base10, bg = neovim.none})
vim.api.nvim_set_hl(0, "helpHeader", {fg = neovim.base15, bg = neovim.none})
vim.api.nvim_set_hl(0, "DiffAdded", {fg = neovim.base07, bg = neovim.none})
vim.api.nvim_set_hl(0, "DiffChanged", {fg = neovim.base09, bg = neovim.none})
vim.api.nvim_set_hl(0, "DiffRemoved", {fg = neovim.base10, bg = neovim.none})
vim.api.nvim_set_hl(0, "DiffAdd", {bg = "#122f2f", fg = neovim.none})
vim.api.nvim_set_hl(0, "DiffChange", {bg = "#222a39", fg = neovim.none})
vim.api.nvim_set_hl(0, "DiffText", {bg = "#2f3f5c", fg = neovim.none})
vim.api.nvim_set_hl(0, "DiffDelete", {bg = "#361c28", fg = neovim.none})
vim.api.nvim_set_hl(0, "IncSearch", {fg = neovim.base06, bg = neovim.base10})
vim.api.nvim_set_hl(0, "Search", {fg = neovim.base01, bg = neovim.base08})
vim.api.nvim_set_hl(0, "TabLine", {link = "StatusLineNC"})
vim.api.nvim_set_hl(0, "TabLineFill", {link = "TabLine"})
vim.api.nvim_set_hl(0, "TabLineSel", {link = "StatusLine"})
vim.api.nvim_set_hl(0, "Title", {fg = neovim.base04, bg = neovim.none})
vim.api.nvim_set_hl(0, "VertSplit", {fg = neovim.base01, bg = neovim.base00})
vim.api.nvim_set_hl(0, "WinSeparator", {fg = neovim.base01, bg = neovim.base00})
vim.api.nvim_set_hl(0, "Boolean", {fg = neovim.base09, bg = neovim.none})
vim.api.nvim_set_hl(0, "Character", {fg = neovim.base14, bg = neovim.none})
vim.api.nvim_set_hl(0, "Comment", {fg = neovim.base03, bg = neovim.none, italic = true})
vim.api.nvim_set_hl(0, "Conceal", {fg = neovim.none, bg = neovim.none})
vim.api.nvim_set_hl(0, "Conditional", {fg = neovim.base09, bg = neovim.none})
vim.api.nvim_set_hl(0, "Constant", {fg = neovim.base04, bg = neovim.none})
vim.api.nvim_set_hl(0, "Decorator", {fg = neovim.base12, bg = neovim.none})
vim.api.nvim_set_hl(0, "Define", {fg = neovim.base09, bg = neovim.none})
vim.api.nvim_set_hl(0, "Delimeter", {fg = neovim.base06, bg = neovim.none})
vim.api.nvim_set_hl(0, "Exception", {fg = neovim.base09, bg = neovim.none})
vim.api.nvim_set_hl(0, "Float", {link = "Number"})
vim.api.nvim_set_hl(0, "Function", {fg = neovim.base08, bg = neovim.none})
vim.api.nvim_set_hl(0, "Identifier", {fg = neovim.base04, bg = neovim.none})
vim.api.nvim_set_hl(0, "Include", {fg = neovim.base09, bg = neovim.none})
vim.api.nvim_set_hl(0, "Keyword", {fg = neovim.base09, bg = neovim.none})
vim.api.nvim_set_hl(0, "Label", {fg = neovim.base09, bg = neovim.none})
vim.api.nvim_set_hl(0, "Number", {fg = neovim.base15, bg = neovim.none})
vim.api.nvim_set_hl(0, "Operator", {fg = neovim.base09, bg = neovim.none})
vim.api.nvim_set_hl(0, "PreProc", {fg = neovim.base09, bg = neovim.none})
vim.api.nvim_set_hl(0, "Repeat", {fg = neovim.base09, bg = neovim.none})
vim.api.nvim_set_hl(0, "Special", {fg = neovim.base04, bg = neovim.none})
vim.api.nvim_set_hl(0, "SpecialChar", {fg = neovim.base04, bg = neovim.none})
vim.api.nvim_set_hl(0, "SpecialComment", {fg = neovim.base08, bg = neovim.none})
vim.api.nvim_set_hl(0, "Statement", {fg = neovim.base09, bg = neovim.none})
vim.api.nvim_set_hl(0, "StorageClass", {fg = neovim.base09, bg = neovim.none})
vim.api.nvim_set_hl(0, "String", {fg = neovim.base14, bg = neovim.none})
vim.api.nvim_set_hl(0, "Structure", {fg = neovim.base09, bg = neovim.none})
vim.api.nvim_set_hl(0, "Tag", {fg = neovim.base04, bg = neovim.none})
vim.api.nvim_set_hl(0, "Todo", {fg = neovim.base13, bg = neovim.none})
vim.api.nvim_set_hl(0, "Type", {fg = neovim.base09, bg = neovim.none})
vim.api.nvim_set_hl(0, "Typedef", {fg = neovim.base09, bg = neovim.none})
vim.api.nvim_set_hl(0, "markdownBlockquote", {fg = neovim.base08, bg = neovim.none})
vim.api.nvim_set_hl(0, "markdownBold", {link = "Bold"})
vim.api.nvim_set_hl(0, "markdownItalic", {link = "Italic"})
vim.api.nvim_set_hl(0, "markdownBoldItalic", {fg = neovim.none, bg = neovim.none, bold = true, italic = true})
vim.api.nvim_set_hl(0, "markdownRule", {link = "Comment"})
vim.api.nvim_set_hl(0, "markdownH1", {fg = neovim.base10, bg = neovim.none})
vim.api.nvim_set_hl(0, "markdownH2", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "markdownH3", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "markdownH4", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "markdownH5", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "markdownH6", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "markdownHeadingDelimiter", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "markdownHeadingRule", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "markdownUrl", {fg = neovim.base14, bg = neovim.none, underline = true})
vim.api.nvim_set_hl(0, "markdownCode", {link = "String"})
vim.api.nvim_set_hl(0, "markdownCodeBlock", {link = "markdownCode"})
vim.api.nvim_set_hl(0, "markdownCodeDelimiter", {link = "markdownCode"})
vim.api.nvim_set_hl(0, "markdownUrl", {link = "String"})
vim.api.nvim_set_hl(0, "markdownListMarker", {fg = neovim.base08, bg = neovim.none})
vim.api.nvim_set_hl(0, "markdownOrderedListMarker", {fg = neovim.base08, bg = neovim.none})
vim.api.nvim_set_hl(0, "@markup", {link = "@none"})
vim.api.nvim_set_hl(0, "@markup.environment", {link = "Macro"})
vim.api.nvim_set_hl(0, "@markup.environment.name", {link = "Type"})
vim.api.nvim_set_hl(0, "@markup.emphasis", {italic = true})
vim.api.nvim_set_hl(0, "@markup.italic", {italic = true})
vim.api.nvim_set_hl(0, "@markup.strikethrough", {strikethrough = true})
vim.api.nvim_set_hl(0, "@markup.strong", {bold = true})
vim.api.nvim_set_hl(0, "@markup.underline", {underline = true})
vim.api.nvim_set_hl(0, "@markup.heading", {link = "Title"})
vim.api.nvim_set_hl(0, "@markup.heading.marker", {link = "markdownHeadingDelimiter"})
vim.api.nvim_set_hl(0, "@markup.heading.1.markdown", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "@markup.heading.2.markdown", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "@markup.heading.3.markdown", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "@markup.heading.4.markdown", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "@markup.heading.5.markdown", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "@markup.heading.6.markdown", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "@markup.heading.7.markdown", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "@markup.heading.8.markdown", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "@markup.link", {link = "markdownUrl"})
vim.api.nvim_set_hl(0, "@markup.link.label", {underline = true})
vim.api.nvim_set_hl(0, "@markup.link.label.symbol", {link = "markdownItalic"})
vim.api.nvim_set_hl(0, "@markup.link.label.markdown_inline", {link = "markdownItalic"})
vim.api.nvim_set_hl(0, "@markup.link.title", {link = "Title"})
vim.api.nvim_set_hl(0, "@markup.link.url", {link = "markdownUrl"})
vim.api.nvim_set_hl(0, "@markup.link.destination", {link = "markdownUrl"})
vim.api.nvim_set_hl(0, "@markup.link.description", {fg = neovim.blend, underline = true, italic = true})
vim.api.nvim_set_hl(0, "@markup.list", {link = "markdownListMarker"})
vim.api.nvim_set_hl(0, "@markup.list.bullet", {link = "markdownListMarker"})
vim.api.nvim_set_hl(0, "@markup.list.checked", {link = "markdownListMarker"})
vim.api.nvim_set_hl(0, "@markup.list.markdown", {link = "markdownListMarker"})
vim.api.nvim_set_hl(0, "@markup.list.ordered", {link = "markdownOrderedListMarker"})
vim.api.nvim_set_hl(0, "@markup.list.unchecked", {link = "markdownListMarker"})
vim.api.nvim_set_hl(0, "@markup.math", {link = "Special"})
vim.api.nvim_set_hl(0, "@markup.raw", {link = "String"})
vim.api.nvim_set_hl(0, "@markup.raw.markdown_inline", {link = "String"})
vim.api.nvim_set_hl(0, "@markup.quote", {link = "markdownBlockquote"})
vim.api.nvim_set_hl(0, "@markup.literal", {link = "markdownCode"})
vim.api.nvim_set_hl(0, "@markup.code.block", {link = "markdownCodeBlock"})
vim.api.nvim_set_hl(0, "@markup.rule", {link = "Comment"})
vim.api.nvim_set_hl(0, "asciidocAttributeEntry", {fg = neovim.base15, bg = neovim.none})
vim.api.nvim_set_hl(0, "asciidocAttributeList", {link = "asciidocAttributeEntry"})
vim.api.nvim_set_hl(0, "asciidocAttributeRef", {link = "asciidocAttributeEntry"})
vim.api.nvim_set_hl(0, "asciidocHLabel", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "asciidocOneLineTitle", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "asciidocQuotedMonospaced", {link = "markdownBlockquote"})
vim.api.nvim_set_hl(0, "asciidocURL", {link = "markdownUrl"})
vim.api.nvim_set_hl(0, "@comment", {link = "Comment"})
vim.api.nvim_set_hl(0, "@error", {fg = neovim.base11, bg = neovim.none})
vim.api.nvim_set_hl(0, "@operator", {link = "Operator"})
vim.api.nvim_set_hl(0, "@punctuation.delimiter", {fg = neovim.base08, bg = neovim.none})
vim.api.nvim_set_hl(0, "@punctuation.bracket", {fg = neovim.base08, bg = neovim.none})
vim.api.nvim_set_hl(0, "@punctuation.special", {fg = neovim.base08, bg = neovim.none})
vim.api.nvim_set_hl(0, "@string", {link = "String"})
vim.api.nvim_set_hl(0, "@string.regex", {fg = neovim.base07, bg = neovim.none})
vim.api.nvim_set_hl(0, "@string.escape", {fg = neovim.base15, bg = neovim.none})
vim.api.nvim_set_hl(0, "@character", {link = "Character"})
vim.api.nvim_set_hl(0, "@boolean", {link = "Boolean"})
vim.api.nvim_set_hl(0, "@number", {link = "Number"})
vim.api.nvim_set_hl(0, "@float", {link = "Float"})
vim.api.nvim_set_hl(0, "@function", {fg = neovim.base12, bg = neovim.none, bold = true})
vim.api.nvim_set_hl(0, "@function.builtin", {fg = neovim.base12, bg = neovim.none})
vim.api.nvim_set_hl(0, "@function.macro", {fg = neovim.base07, bg = neovim.none})
vim.api.nvim_set_hl(0, "@method", {fg = neovim.base07, bg = neovim.none})
vim.api.nvim_set_hl(0, "@constructor", {fg = neovim.base09, bg = neovim.none})
vim.api.nvim_set_hl(0, "@parameter", {fg = neovim.base04, bg = neovim.none})
vim.api.nvim_set_hl(0, "@keyword", {fg = neovim.base09, bg = neovim.none})
vim.api.nvim_set_hl(0, "@keyword.function", {fg = neovim.base08, bg = neovim.none})
vim.api.nvim_set_hl(0, "@keyword.operator", {fg = neovim.base08, bg = neovim.none})
vim.api.nvim_set_hl(0, "@conditional", {fg = neovim.base09, bg = neovim.none})
vim.api.nvim_set_hl(0, "@repeat", {fg = neovim.base09, bg = neovim.none})
vim.api.nvim_set_hl(0, "@label", {fg = neovim.base15, bg = neovim.none})
vim.api.nvim_set_hl(0, "@include", {fg = neovim.base09, bg = neovim.none})
vim.api.nvim_set_hl(0, "@exception", {fg = neovim.base15, bg = neovim.none})
vim.api.nvim_set_hl(0, "@type", {link = "Type"})
vim.api.nvim_set_hl(0, "@type.builtin", {link = "Type"})
vim.api.nvim_set_hl(0, "@attribute", {fg = neovim.base15, bg = neovim.none})
vim.api.nvim_set_hl(0, "@field", {fg = neovim.base04, bg = neovim.none})
vim.api.nvim_set_hl(0, "@property", {fg = neovim.base10, bg = neovim.none})
vim.api.nvim_set_hl(0, "@variable", {fg = neovim.base04, bg = neovim.none})
vim.api.nvim_set_hl(0, "@variable.builtin", {fg = neovim.base04, bg = neovim.none})
vim.api.nvim_set_hl(0, "@constant", {fg = neovim.base14, bg = neovim.none})
vim.api.nvim_set_hl(0, "@constant.builtin", {fg = neovim.base07, bg = neovim.none})
vim.api.nvim_set_hl(0, "@constant.macro", {fg = neovim.base07, bg = neovim.none})
vim.api.nvim_set_hl(0, "@namespace", {fg = neovim.base07, bg = neovim.none})
vim.api.nvim_set_hl(0, "@symbol", {fg = neovim.base15, bg = neovim.none, bold = true})
vim.api.nvim_set_hl(0, "@text", {fg = neovim.base04, bg = neovim.none})
vim.api.nvim_set_hl(0, "@text.strong", {fg = neovim.none, bg = neovim.none})
vim.api.nvim_set_hl(0, "@text.emphasis", {fg = neovim.base10, bg = neovim.none, bold = true})
vim.api.nvim_set_hl(0, "@text.underline", {fg = neovim.base10, bg = neovim.none, underline = true})
vim.api.nvim_set_hl(0, "@text.strike", {fg = neovim.base10, bg = neovim.none, strikethrough = true})
vim.api.nvim_set_hl(0, "@text.title", {fg = neovim.base10, bg = neovim.none})
vim.api.nvim_set_hl(0, "@text.literal", {fg = neovim.base04, bg = neovim.none})
vim.api.nvim_set_hl(0, "@text.uri", {fg = neovim.base14, bg = neovim.none, underline = true})
vim.api.nvim_set_hl(0, "@tag", {fg = neovim.base09, bg = neovim.none})
vim.api.nvim_set_hl(0, "@tag.attribute", {fg = neovim.base15, bg = neovim.none})
vim.api.nvim_set_hl(0, "@tag.delimiter", {fg = neovim.base15, bg = neovim.none})
vim.api.nvim_set_hl(0, "@tag.builtin.tsx", {link = "@tag.tsx"})
vim.api.nvim_set_hl(0, "@reference", {fg = neovim.base04, bg = neovim.none})
vim.api.nvim_set_hl(0, "NvimInternalError", {fg = neovim.base00, bg = neovim.base08})
vim.api.nvim_set_hl(0, "NormalFloat", {fg = neovim.base05, bg = neovim.blend})
vim.api.nvim_set_hl(0, "FloatBorder", {fg = neovim.blend, bg = neovim.blend})
vim.api.nvim_set_hl(0, "NormalNC", {fg = neovim.base05, bg = neovim.base00})
vim.api.nvim_set_hl(0, "TermCursor", {fg = neovim.base00, bg = neovim.base04})
vim.api.nvim_set_hl(0, "TermCursorNC", {fg = neovim.base00, bg = neovim.base04})
vim.api.nvim_set_hl(0, "StatusLine", {fg = neovim.base04, bg = neovim.base00})
vim.api.nvim_set_hl(0, "StatusLineNC", {fg = neovim.base04, bg = neovim.base01})
vim.api.nvim_set_hl(0, "StatusReplace", {fg = neovim.base00, bg = neovim.base08})
vim.api.nvim_set_hl(0, "StatusInsert", {fg = neovim.base00, bg = neovim.base12})
vim.api.nvim_set_hl(0, "StatusVisual", {fg = neovim.base00, bg = neovim.base14})
vim.api.nvim_set_hl(0, "StatusTerminal", {fg = neovim.base00, bg = neovim.base11})
vim.api.nvim_set_hl(0, "StatusNormal", {fg = neovim.base00, bg = neovim.base15})
vim.api.nvim_set_hl(0, "StatusCommand", {fg = neovim.base00, bg = neovim.base13})
vim.api.nvim_set_hl(0, "StatusLineDiagnosticWarn", {fg = neovim.base14, bg = neovim.base00, bold = true})
vim.api.nvim_set_hl(0, "StatusLineDiagnosticError", {fg = neovim.base10, bg = neovim.base00, bold = true})
vim.api.nvim_set_hl(0, "TelescopeBorder", {fg = neovim.blend, bg = neovim.blend})
vim.api.nvim_set_hl(0, "TelescopePromptBorder", {fg = neovim.base02, bg = neovim.base02})
vim.api.nvim_set_hl(0, "TelescopePromptNormal", {fg = neovim.base05, bg = neovim.base02})
vim.api.nvim_set_hl(0, "TelescopePromptPrefix", {fg = neovim.base08, bg = neovim.base02})
vim.api.nvim_set_hl(0, "TelescopeNormal", {fg = neovim.none, bg = neovim.blend})
vim.api.nvim_set_hl(0, "TelescopePreviewTitle", {fg = neovim.base02, bg = neovim.base12})
vim.api.nvim_set_hl(0, "TelescopePromptTitle", {fg = neovim.base02, bg = neovim.base11})
vim.api.nvim_set_hl(0, "TelescopeResultsTitle", {fg = neovim.blend, bg = neovim.blend})
vim.api.nvim_set_hl(0, "TelescopeSelection", {fg = neovim.none, bg = neovim.base02})
vim.api.nvim_set_hl(0, "TelescopePreviewLine", {fg = neovim.none, bg = neovim.base01})
vim.api.nvim_set_hl(0, "TelescopeMatching", {fg = neovim.base08, bg = neovim.none, bold = true, italic = true})
vim.api.nvim_set_hl(0, "NotifyERRORBorder", {fg = neovim.base08, bg = neovim.none})
vim.api.nvim_set_hl(0, "NotifyWARNBorder", {fg = neovim.base14, bg = neovim.none})
vim.api.nvim_set_hl(0, "NotifyINFOBorder", {fg = neovim.base05, bg = neovim.none})
vim.api.nvim_set_hl(0, "NotifyDEBUGBorder", {fg = neovim.base13, bg = neovim.none})
vim.api.nvim_set_hl(0, "NotifyTRACEBorder", {fg = neovim.base13, bg = neovim.none})
vim.api.nvim_set_hl(0, "NotifyERRORIcon", {fg = neovim.base08, bg = neovim.none})
vim.api.nvim_set_hl(0, "NotifyWARNIcon", {fg = neovim.base14, bg = neovim.none})
vim.api.nvim_set_hl(0, "NotifyINFOIcon", {fg = neovim.base05, bg = neovim.none})
vim.api.nvim_set_hl(0, "NotifyDEBUGIcon", {fg = neovim.base13, bg = neovim.none})
vim.api.nvim_set_hl(0, "NotifyTRACEIcon", {fg = neovim.base13, bg = neovim.none})
vim.api.nvim_set_hl(0, "NotifyERRORTitle", {fg = neovim.base08, bg = neovim.none})
vim.api.nvim_set_hl(0, "NotifyWARNTitle", {fg = neovim.base14, bg = neovim.none})
vim.api.nvim_set_hl(0, "NotifyINFOTitle", {fg = neovim.base05, bg = neovim.none})
vim.api.nvim_set_hl(0, "NotifyDEBUGTitle", {fg = neovim.base13, bg = neovim.none})
vim.api.nvim_set_hl(0, "NotifyTRACETitle", {fg = neovim.base13, bg = neovim.none})
vim.api.nvim_set_hl(0, "CmpItemAbbr", {fg = "#adadad", bg = neovim.none})
vim.api.nvim_set_hl(0, "CmpItemAbbrMatch", {fg = neovim.base05, bg = neovim.none, bold = true})
vim.api.nvim_set_hl(0, "CmpItemAbbrMatchFuzzy", {fg = neovim.base04, bg = neovim.none, bold = true})
vim.api.nvim_set_hl(0, "CmpItemMenu", {fg = neovim.base04, bg = neovim.none, italic = true})
vim.api.nvim_set_hl(0, "CmpItemKindInterface", {fg = neovim.base01, bg = neovim.base08})
vim.api.nvim_set_hl(0, "CmpItemKindColor", {fg = neovim.base01, bg = neovim.base08})
vim.api.nvim_set_hl(0, "CmpItemKindTypeParameter", {fg = neovim.base01, bg = neovim.base08})
vim.api.nvim_set_hl(0, "CmpItemKindText", {fg = neovim.base01, bg = neovim.base09})
vim.api.nvim_set_hl(0, "CmpItemKindEnum", {fg = neovim.base01, bg = neovim.base09})
vim.api.nvim_set_hl(0, "CmpItemKindKeyword", {fg = neovim.base01, bg = neovim.base09})
vim.api.nvim_set_hl(0, "CmpItemKindConstant", {fg = neovim.base01, bg = neovim.base10})
vim.api.nvim_set_hl(0, "CmpItemKindConstructor", {fg = neovim.base01, bg = neovim.base10})
vim.api.nvim_set_hl(0, "CmpItemKindReference", {fg = neovim.base01, bg = neovim.base10})
vim.api.nvim_set_hl(0, "CmpItemKindFunction", {fg = neovim.base01, bg = neovim.base11})
vim.api.nvim_set_hl(0, "CmpItemKindStruct", {fg = neovim.base01, bg = neovim.base11})
vim.api.nvim_set_hl(0, "CmpItemKindClass", {fg = neovim.base01, bg = neovim.base11})
vim.api.nvim_set_hl(0, "CmpItemKindModule", {fg = neovim.base01, bg = neovim.base11})
vim.api.nvim_set_hl(0, "CmpItemKindOperator", {fg = neovim.base01, bg = neovim.base11})
vim.api.nvim_set_hl(0, "CmpItemKindField", {fg = neovim.base01, bg = neovim.base12})
vim.api.nvim_set_hl(0, "CmpItemKindProperty", {fg = neovim.base01, bg = neovim.base12})
vim.api.nvim_set_hl(0, "CmpItemKindEvent", {fg = neovim.base01, bg = neovim.base12})
vim.api.nvim_set_hl(0, "CmpItemKindUnit", {fg = neovim.base01, bg = neovim.base13})
vim.api.nvim_set_hl(0, "CmpItemKindSnippet", {fg = neovim.base01, bg = neovim.base13})
vim.api.nvim_set_hl(0, "CmpItemKindFolder", {fg = neovim.base01, bg = neovim.base13})
vim.api.nvim_set_hl(0, "CmpItemKindVariable", {fg = neovim.base01, bg = neovim.base14})
vim.api.nvim_set_hl(0, "CmpItemKindFile", {fg = neovim.base01, bg = neovim.base14})
vim.api.nvim_set_hl(0, "CmpItemKindMethod", {fg = neovim.base01, bg = neovim.base15})
vim.api.nvim_set_hl(0, "CmpItemKindValue", {fg = neovim.base01, bg = neovim.base15})
vim.api.nvim_set_hl(0, "CmpItemKindEnumMember", {fg = neovim.base01, bg = neovim.base15})
vim.api.nvim_set_hl(0, "NvimTreeImageFile", {fg = neovim.base12, bg = neovim.none})
vim.api.nvim_set_hl(0, "NvimTreeFolderIcon", {fg = neovim.base12, bg = neovim.none})
vim.api.nvim_set_hl(0, "NvimTreeWinSeparator", {fg = neovim.base00, bg = neovim.base00})
vim.api.nvim_set_hl(0, "NvimTreeFolderName", {fg = neovim.base09, bg = neovim.none})
vim.api.nvim_set_hl(0, "NvimTreeIndentMarker", {fg = neovim.base02, bg = neovim.none})
vim.api.nvim_set_hl(0, "NvimTreeEmptyFolderName", {fg = neovim.base15, bg = neovim.none})
vim.api.nvim_set_hl(0, "NvimTreeOpenedFolderName", {fg = neovim.base15, bg = neovim.none})
vim.api.nvim_set_hl(0, "NvimTreeNormal", {fg = neovim.base04, bg = neovim.base00})
vim.api.nvim_set_hl(0, "NeogitBranch", {fg = neovim.base10, bg = neovim.none})
vim.api.nvim_set_hl(0, "NeogitRemote", {fg = neovim.base09, bg = neovim.none})
vim.api.nvim_set_hl(0, "NeogitHunkHeader", {fg = neovim.base04, bg = neovim.base02})
vim.api.nvim_set_hl(0, "NeogitHunkHeaderHighlight", {fg = neovim.base04, bg = neovim.base03})
vim.api.nvim_set_hl(0, "GitSignsCurrentLineBlame", {link = "Comment"})
vim.api.nvim_set_hl(0, "HydraRed", {fg = neovim.base12, bg = neovim.none})
vim.api.nvim_set_hl(0, "HydraBlue", {fg = neovim.base09, bg = neovim.none})
vim.api.nvim_set_hl(0, "HydraAmaranth", {fg = neovim.base10, bg = neovim.none})
vim.api.nvim_set_hl(0, "HydraTeal", {fg = neovim.base08, bg = neovim.none})
vim.api.nvim_set_hl(0, "HydraHint", {fg = neovim.none, bg = neovim.blend})
vim.api.nvim_set_hl(0, "alpha1", {fg = neovim.base03, bg = neovim.none})
vim.api.nvim_set_hl(0, "alpha2", {fg = neovim.base04, bg = neovim.none})
vim.api.nvim_set_hl(0, "alpha3", {fg = neovim.base03, bg = neovim.none})
vim.api.nvim_set_hl(0, "CodeBlock", {fg = neovim.none, bg = neovim.base01})
vim.api.nvim_set_hl(0, "BufferLineDiagnostic", {fg = neovim.base10, bg = neovim.none, bold = true})
vim.api.nvim_set_hl(0, "BufferLineDiagnosticVisible", {fg = neovim.base10, bg = neovim.none, bold = true})
vim.api.nvim_set_hl(0, "htmlH1", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "mkdRule", {link = "markdownRule"})
vim.api.nvim_set_hl(0, "mkdListItem", {link = "markdownListMarker"})
vim.api.nvim_set_hl(0, "mkdListItemCheckbox", {link = "markdownListMarker"})
vim.api.nvim_set_hl(0, "VimwikiHeader1", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "VimwikiHeader2", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "VimwikiHeader3", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "VimwikiHeader4", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "VimwikiHeader5", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "VimwikiHeader6", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "VimwikiHeaderChar", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "VimwikiList", {link = "markdownListMarker"})
vim.api.nvim_set_hl(0, "VimwikiLink", {link = "markdownUrl"})
vim.api.nvim_set_hl(0, "VimwikiCode", {link = "markdownCode"})
vim.api.nvim_set_hl(0, "FlashLabel", {fg = neovim.base05, bg = neovim.base00, bold = true})
vim.api.nvim_set_hl(0, "BlinkCmpMenu", {link = "Pmenu"})
vim.api.nvim_set_hl(0, "BlinkCmpLabel", {fg = neovim.base04, bg = neovim.base01})
vim.api.nvim_set_hl(0, "BlinkCmpMenuSelection", {fg = neovim.none, bg = neovim.base02})
vim.api.nvim_set_hl(0, "BlinkCmpLabelMatch", {fg = neovim.base14, bg = neovim.none, bold = true})
vim.api.nvim_set_hl(0, "BlinkCmpKind", {fg = neovim.base01, bg = neovim.base09})
vim.api.nvim_set_hl(0, "BlinkCmpKindText", {fg = neovim.base01, bg = neovim.base09})
vim.api.nvim_set_hl(0, "BlinkCmpKindEnum", {fg = neovim.base01, bg = neovim.base09})
vim.api.nvim_set_hl(0, "BlinkCmpKindKeyword", {fg = neovim.base01, bg = neovim.base09})
vim.api.nvim_set_hl(0, "BlinkCmpKindConstant", {fg = neovim.base01, bg = neovim.base10})
vim.api.nvim_set_hl(0, "BlinkCmpKindConstructor", {fg = neovim.base01, bg = neovim.base10})
vim.api.nvim_set_hl(0, "BlinkCmpKindReference", {fg = neovim.base01, bg = neovim.base10})
vim.api.nvim_set_hl(0, "BlinkCmpKindFunction", {fg = neovim.base01, bg = neovim.base11})
vim.api.nvim_set_hl(0, "BlinkCmpKindStruct", {fg = neovim.base01, bg = neovim.base11})
vim.api.nvim_set_hl(0, "BlinkCmpKindClass", {fg = neovim.base01, bg = neovim.base11})
vim.api.nvim_set_hl(0, "BlinkCmpKindModule", {fg = neovim.base01, bg = neovim.base11})
vim.api.nvim_set_hl(0, "BlinkCmpKindOperator", {fg = neovim.base01, bg = neovim.base11})
vim.api.nvim_set_hl(0, "BlinkCmpKindField", {fg = neovim.base01, bg = neovim.base12})
vim.api.nvim_set_hl(0, "BlinkCmpKindProperty", {fg = neovim.base01, bg = neovim.base14})
vim.api.nvim_set_hl(0, "BlinkCmpKindEvent", {fg = neovim.base01, bg = neovim.base12})
vim.api.nvim_set_hl(0, "BlinkCmpKindUnit", {fg = neovim.base01, bg = neovim.base13})
vim.api.nvim_set_hl(0, "BlinkCmpKindSnippet", {fg = neovim.base01, bg = neovim.base13})
vim.api.nvim_set_hl(0, "BlinkCmpKindFolder", {fg = neovim.base01, bg = neovim.base13})
vim.api.nvim_set_hl(0, "BlinkCmpKindVariable", {fg = neovim.base01, bg = neovim.base14})
vim.api.nvim_set_hl(0, "BlinkCmpKindFile", {fg = neovim.base01, bg = neovim.base14})
vim.api.nvim_set_hl(0, "BlinkCmpKindMethod", {fg = neovim.base01, bg = neovim.base15})
vim.api.nvim_set_hl(0, "BlinkCmpKindValue", {fg = neovim.base01, bg = neovim.base15})
vim.api.nvim_set_hl(0, "BlinkCmpKindEnumMember", {fg = neovim.base01, bg = neovim.base15})
vim.api.nvim_set_hl(0, "BlinkCmpDoc", {link = "Pmenu"})
return {neovim = neovim}