-- @generated by hotpot.nvim using fennel 1.6.1, edits to this file may be lost
local compile = require("hotpot.api.compile")
return compile.directory("./fnl", {force = true, atomic = true, target = "./lua"})